"""change article summary to text

Revision ID: 34c6cb3372f6
Revises: 9d8c7b6a5f4e
Create Date: 2026-05-12 10:52:26.632221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c6cb3372f6'
down_revision: Union[str, None] = '9d8c7b6a5f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'summary',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###

def upgrade():
    op.drop_column("articles", "summary")

def downgrade():
    op.add_column(
        "articles",
        sa.Column("summary", sa.Text(), nullable=True)
    )